---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Deploy Nginx reverse proxy configuration template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/epicbook
  notify: Restart Nginx

- name: Enable EpicBook Nginx site
  file:
    src: /etc/nginx/sites-available/epicbook
    dest: /etc/nginx/sites-enabled/epicbook
    state: link
  notify: Restart Nginx

- name: Ensure Nginx is running and enabled at boot
  service:
    name: nginx
    state: started
    enabled: yes